name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:9

    steps:
    - name: Use Debian 9 official archive sources
      run: |
        echo "deb http://archive.debian.org/debian stretch main contrib non-free" > /etc/apt/sources.list
        echo "deb http://archive.debian.org/debian-security stretch/updates main contrib non-free" >> /etc/apt/sources.list
        # 禁用验证（因为 archive.debian.org 上的签名已过期）
        echo 'Acquire::Check-Valid-Until "false";' > /etc/apt/apt.conf.d/99no-check-valid-until
        apt-get update

    - name: Install dependencies (including sudo)
      run: |
        apt-get install -y sudo git curl tar gcc make libc6-dev

    - name: Clone AdaptixC2 and run pre-install
      run: |
        git clone https://github.com/Adaptix-Framework/AdaptixC2.git
        cd AdaptixC2
        chmod +x pre_install_linux.sh
        ./pre_install_linux.sh

    - name: Print glibc version
      run: |
        ldd --version | head -n 1

    - name: Package dist folder
      run: |
        cd AdaptixC2/dist
        tar -czf adaptixc2_build.tar.gz *

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: adaptixc2_build
        path: AdaptixC2/dist/adaptixc2_build.tar.gz
