
name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: centos:7

    steps:
    - name: Configure YUM mirrors and install dependencies
      run: |
        curl -o /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-7.repo
        yum clean all
        yum makecache
        yum -y groupinstall "Development Tools"
        yum -y install sudo git curl tar gcc make cmake openssl-devel glibc-devel libcap mingw64-gcc

    - name: Install Go 1.24.3
      run: |
        curl -LO https://go.dev/dl/go1.24.3.linux-amd64.tar.gz
        tar -C /usr/local -xzf go1.24.3.linux-amd64.tar.gz
        echo "export PATH=$PATH:/usr/local/go/bin" >> /etc/profile
        export PATH=$PATH:/usr/local/go/bin
        go version

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Clone AdaptixC2
      run: git clone https://github.com/Adaptix-Framework/AdaptixC2.git

    - name: Build server and extenders
      run: |
        export PATH=$PATH:/usr/local/go/bin
        cd AdaptixC2
        make server
        make extenders

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: adaptix-dist
        path: AdaptixC2/dist

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: adaptix-dist
        path: dist

    - name: Package dist folder
      run: |
        cd dist
        tar -czf adaptix.server.linux-amd64.tar.gz *

    - name: Create GitHub Release and upload artifact
      uses: softprops/action-gh-release@v2
      with:
        files: dist/adaptix.server.linux-amd64.tar.gz
