name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    container:
      image: centos:7

    steps:
    - name: Configure YUM mirrors and install dependencies
      run: |
        # 备份原有 repo 文件
        mv /etc/yum.repos.d/CentOS-Base.repo /etc/yum.repos.d/CentOS-Base.repo.bak || true
    
        # 使用阿里云镜像
        curl -o /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-7.repo
    
        # 清理缓存并更新
        yum clean all
        yum makecache
    
        # 安装依赖
        yum -y groupinstall "Development Tools"
        yum -y install sudo git curl tar gcc make cmake openssl-devel glibc-devel libcap mingw64-gcc


    - name: Install Go 1.24.3
      run: |
        curl -LO https://go.dev/dl/go1.24.3.linux-amd64.tar.gz
        tar -C /usr/local -xzf go1.24.3.linux-amd64.tar.gz
        echo "export PATH=$PATH:/usr/local/go/bin" >> /etc/profile
        export PATH=$PATH:/usr/local/go/bin
        go version

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Clone AdaptixC2
      run: |
        git clone https://github.com/Adaptix-Framework/AdaptixC2.git

    - name: Build server and extenders
      run: |
        export PATH=$PATH:/usr/local/go/bin
        cd AdaptixC2
        make server
        make extenders

    - name: Print glibc version
      run: |
        ldd --version | head -n 1

    - name: Package dist folder
      run: |
        cd AdaptixC2/dist
        tar -czf adaptix.server.linux-amd64.tar.gz *

    - name: Create GitHub Release and upload artifact
      uses: softprops/action-gh-release@v2
      with:
        files: AdaptixC2/dist/adaptix.server.linux-amd64.tar.gz
