name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:9

    steps:
    - name: Use faster Debian mirror
      run: |
        sed -i 's|http://deb.debian.org|https://mirrors.tuna.tsinghua.edu.cn|g' /etc/apt/sources.list
        apt-get update

    - name: Install dependencies (including sudo)
      run: |
        apt-get install -y sudo git curl tar gcc make libc6-dev

    - name: Clone AdaptixC2 and run pre-install
      run: |
        git clone https://github.com/Adaptix-Framework/AdaptixC2.git
        cd AdaptixC2
        chmod +x pre_install_linux.sh
        ./pre_install_linux.sh

    - name: Print glibc version
      run: |
        ldd --version | head -n 1

    - name: Package dist folder
      run: |
        cd AdaptixC2/dist
        tar -czf adaptixc2_build.tar.gz *

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: adaptixc2_build
        path: AdaptixC2/dist/adaptixc2_build.tar.gz
