name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:10

    steps:
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y sudo git curl tar gcc make cmake libssl-dev libc6-dev libcap2-bin mingw-w64

    - name: Install Go 1.24.3
      run: |
        curl -LO https://go.dev/dl/go1.24.3.linux-amd64.tar.gz
        tar -C /usr/local -xzf go1.24.3.linux-amd64.tar.gz
        echo "export PATH=$PATH:/usr/local/go/bin" >> /etc/profile
        export PATH=$PATH:/usr/local/go/bin
        go version

    - name: Clone AdaptixC2 and run pre-install
      run: |
        git clone https://github.com/Adaptix-Framework/AdaptixC2.git

    - name: Build server and extenders
      run: |
        export PATH=$PATH:/usr/local/go/bin
        cd AdaptixC2
        make server
        make extenders

    - name: Print glibc version
      run: |
        ldd --version | head -n 1

    - name: Package dist folder
      run: |
        cd AdaptixC2/dist
        tar -czf adaptixc2_build.tar.gz *

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: adaptixc2_build
        path: AdaptixC2/dist/adaptixc2_build.tar.gz
